name: Build and Release [Beta]

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Java Environment
      uses: actions/setup-java@v3
      with:
        java-version: 19
        distribution: 'temurin'
        # Testing cache
        cache: 'maven'

    - name: Build and Test
      run: mvn clean package install

    - name: Deploy to GitHub Releases
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.GITHUB_REPOSITORY }}-v${{ env.GITHUB_SHA }}
        path: target/*.jar
    
    - name: Set outputs
      id: short_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        body: 'Release'
        name: mcMMO Automation Compile ${{ env.GITHUB_SHA }}
        draft: false
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: MediumCraft/mcMMO
